globals:
  project_home: $LEX_HOME
  service_module: lex_services
  datastore_module: lex_datastores


service_objects:
  postgres:
      class: PostgreSQLService
      init_params:
        - name: host
          value: localhost
    
        - name: port
          value: 5432
    
        - name: dbname
          value: lexdb

        - name: schema
          value: public
    
        - name: username
          value: lexdba
    
        - name: password
          value: $LEX_DB_PASSWORD

        - name: connect_timeout
          value: 5


datastores:

  db:
    class: PostgresDatastore
    init_params:
        
    channel_select_function: 
    channels:
        

ingest_targets:
  db:
    datastore: db
    checkpoint_interval: 1000

