#!/usr/bin/env python

'''
Usage:
    normalize <filename> 
    normalize -s
Options:
    -s --stdin      read input from standard in
'''

import os, sys
import json
import docopt
from mercury.utils import read_stdin



def normalize_line(input_line):

    # Is this the header line?
    if 'Application' in input_line:
        output_line = input_line.replace('Application Status', 'Status').replace('Application Date', 'Date')        
    
    elif 'Withdrawn' in input_line:
        output_line = input_line.replace('Withdrawn by Applicant', 'Withdrawn')
    else:
        output_line = input_line

    return output_line.strip().replace(' ', '|')
    

def main(args):
    
    if args['--stdin']:

        for line in read_stdin():
            print(normalize_line(line).strip())
            
    else:
        input_filename = args['<filename>']

        with open(input_filename, 'r') as f:
            for line in f:
                print(normalize_line(line).strip())
        

if __name__ == '__main__':
    args = docopt.docopt(__doc__)
    main(args)