

TRUNCATE TABLE dim_time_minute CASCADE;
TRUNCATE TABLE dim_time_hour CASCADE;
TRUNCATE TABLE dim_date_day CASCADE;
TRUNCATE TABLE dim_date_month CASCADE;
TRUNCATE TABLE dim_date_year CASCADE;
TRUNCATE TABLE dim_permit_type CASCADE;

